config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/exams')

  resources :exams

  resources :groups

  resources :mutations

  resources :patients

  resources :institutions

  resources :doctors

  resources :genotypes

  resources :drugs

end

app/models/institution.rb
# == Schema Information
#
# Table name: institutions
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  abbreviation :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#

class Institution < ActiveRecord::Base
  validates :name, presence: true

  def self.search(name, abbreviation)
    query = all
    query = query.where('name LIKE ?', "%#{name}%") if name
    query = query.where('abbreviation LIKE ?', "%#{abbreviation}%") if abbreviation

    query
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: [:show, :edit, :update, :destroy]

  # GET /institutions
  # GET /institutions.json
  def index
    @institutions = Institution.search(params[:name], params[:abbreviation])
      .order('name ASC').paginate(page: params[:page])
  end

  # GET /institutions/1
  # GET /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions
  # POST /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to institutions_url, notice: 'Institution was successfully created.' }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1
  # PATCH/PUT /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to institutions_url, notice: 'Institution was successfully updated.' }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1
  # DELETE /institutions/1.json
  def destroy
    @institution.destroy
    respond_to do |format|
      format.html { redirect_to institutions_url, notice: 'Institution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institution_params
      params.require(:institution).permit(:name, :abbreviation)
    end
end

app/views/institutions/_form.html.erb
<%= form_for @institution, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-lg-1 control-label' %>
    <div class="col-lg-5">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :abbreviation, class: 'col-lg-1 control-label' %>
    <div class="col-lg-5">
      <%= f.text_field :abbreviation, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-5">
      <%= submit(f) %>
      <%= cancel(institutions_path) %>
    </div>
  </div>
<% end %>

app/views/institutions/_search.html.erb
<%= filter_panel do %>
  <%= form_tag institutions_path, method: 'get', class: 'form-inline', id: 'institution_search' do %>
    <div class="form-group">
      <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "Name" %>

      <%= text_field_tag :abbreviation, params[:abbreviation], class: "form-control", placeholder: "Abbreviation" %>

      <%= search_button %>

      <%= clear_button(institutions_path) %>
    </div>
  <% end %>
<% end %>

app/views/institutions/_table.html.erb
<%= table(@institutions) do %>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abbreviation</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @institutions.each do |m| %>
      <tr>
        <td><%= m.name %></td>
        <td><%= m.abbreviation %></td>
        <td>
          <%= edit_link(edit_institution_path(m)) %>
          <%= destroy_link(institution_path(m)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
<% end %>

app/views/institutions/edit.html.erb
<%- model_class = Institution -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/institutions/index.html.erb
<%= page_header("Institutions #{new_link(new_institution_path)}") %>

<%= render 'search' %>

<%= render 'table' %>

app/views/institutions/new.html.erb
<%= page_header("New Institution") %>

<%= render 'form' %>

app/views/institutions/show.html.erb
<%- model_class = Institution -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @institution.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:abbreviation) %>:</strong></dt>
  <dd><%= @institution.abbreviation %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              institutions_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_institution_path(@institution), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              institution_path(@institution),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>