config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/exams')

  resources :exams

  resources :groups

  resources :mutations

  resources :patients

  resources :institutions

  resources :doctors

  resources :genotypes

  resources :drugs

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  code       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Group < ActiveRecord::Base
  validates :code, presence: true, uniqueness: true

  def self.search(code)
    query = all
    query = query.where('code LIKE ?', "%#{code}%") if code
    query
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.search(params[:code]).order('code ASC').paginate(page: params[:page])
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_url, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:code)
    end
end

app/views/groups/_form.html.erb
<%= form_for @group, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :code, class: 'col-lg-1 control-label' %>
    <div class="col-lg-5">
      <%= f.text_field :code, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-5">
      <%= submit(f) %>
      <%= cancel(groups_path) %>
    </div>
  </div>
<% end %>

app/views/groups/_search.html.erb
<%= filter_panel do %>
  <%= form_tag groups_path, method: 'get', class: 'form-inline', id: 'group_search' do %>
    <div class="form-group">
      <%= text_field_tag :code, params[:code], class: "form-control", placeholder: "Code" %>

      <%= search_button %>

      <%= clear_button(groups_path) %>
    </div>
  <% end %>
<% end %>

app/views/groups/_table.html.erb
<%= table(@groups) do %>
  <thead>
    <tr>
      <th>Code</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |m| %>
      <tr>
        <td><%= m.code %></td>
        <td>
          <%= edit_link(edit_group_path(m)) %>
          <%= destroy_link(group_path(m)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
<% end %>

app/views/groups/edit.html.erb
<%= page_header("Edit Group") %>

<%= render 'form' %>

app/views/groups/index.html.erb
<%= page_header("Groups #{new_link(new_group_path)}") %>

<%= render 'search' %>

<%= render 'table' %>

app/views/groups/new.html.erb
<%= page_header("New Group") %>

<%= render 'form' %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @group.code %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>