config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/exams')

  resources :exams

  resources :groups

  resources :mutations

  resources :patients

  resources :institutions

  resources :doctors

  resources :genotypes

  resources :drugs

end

app/controllers/genotypes_controller.rb
class GenotypesController < ApplicationController
  before_action :set_genotype, only: [:show, :edit, :update, :destroy]

  # GET /genotypes
  # GET /genotypes.json
  def index
    @genotypes = Genotype.search(params[:code]).order('code ASC').paginate(page: params[:page])
  end

  # GET /genotypes/1
  # GET /genotypes/1.json
  def show
  end

  # GET /genotypes/new
  def new
    @genotype = Genotype.new
  end

  # GET /genotypes/1/edit
  def edit
  end

  # POST /genotypes
  # POST /genotypes.json
  def create
    @genotype = Genotype.new(genotype_params)

    respond_to do |format|
      if @genotype.save
        format.html { redirect_to genotypes_url, notice: 'Genotype was successfully created.' }
        format.json { render :show, status: :created, location: @genotype }
      else
        format.html { render :new }
        format.json { render json: @genotype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genotypes/1
  # PATCH/PUT /genotypes/1.json
  def update
    respond_to do |format|
      if @genotype.update(genotype_params)
        format.html { redirect_to genotypes_url, notice: 'Genotype was successfully updated.' }
        format.json { render :show, status: :ok, location: @genotype }
      else
        format.html { render :edit }
        format.json { render json: @genotype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genotypes/1
  # DELETE /genotypes/1.json
  def destroy
    @genotype.destroy
    respond_to do |format|
      format.html { redirect_to genotypes_url, notice: 'Genotype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genotype
      @genotype = Genotype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genotype_params
      params.require(:genotype).permit(:code)
    end
end

app/views/genotypes/_form.html.erb
<%= form_for @genotype, html: { class: 'form-horizontal', role: 'form' } do |f| %>
  <div class="form-group">
    <%= f.label :code, class: 'col-lg-1 control-label' %>
    <div class="col-lg-5">
      <%= f.text_field :code, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-5">
      <%= submit(f) %>
      <%= cancel(genotypes_path) %>
    </div>
  </div>
<% end %>

app/views/genotypes/_search.html.erb
<%= filter_panel do %>
  <%= form_tag genotypes_path, method: 'get', class: 'form-inline', id: 'genotype_search' do %>
    <div class="form-group">
      <%= text_field_tag :code, params[:code], class: "form-control", placeholder: "Code" %>

      <%= search_button %>

      <%= clear_button(genotypes_path) %>
    </div>
  <% end %>
<% end %>

app/views/genotypes/_table.html.erb
<%= table(@genotypes) do %>
  <thead>
    <tr>
      <th>Code</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @genotypes.each do |m| %>
      <tr>
        <td><%= m.code %></td>
        <td>
          <%= edit_link(edit_genotype_path(m)) %>
          <%= destroy_link(genotype_path(m)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
<% end %>

app/views/genotypes/edit.html.erb
<%= page_header("Edit Genotype") %>

<%= render 'form' %>

app/views/genotypes/index.html.erb
<%= page_header("Genotypes #{new_link(new_genotype_path)}") %>

<%= render 'search' %>

<%= render 'table' %>

app/views/genotypes/new.html.erb
<%= page_header("New Genotype") %>

<%= render 'form' %>

app/views/genotypes/show.html.erb
<%- model_class = Genotype -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @genotype.code %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              genotypes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_genotype_path(@genotype), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              genotype_path(@genotype),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>