config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/exams')

  resources :exams

  resources :groups

  resources :mutations

  resources :patients

  resources :institutions

  resources :doctors

  resources :genotypes

  resources :drugs

end

app/views/layouts/_container.html.erb
<div id="page-wrapper">
  <%= render 'shared/notice' %>
  <%= yield %>
</div>

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle Navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Hepatitis Analysis</a>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <%= nav_link "Exams",        exams_path,        "stethoscope" %>
      <%= nav_link "Patients",     patients_path,     "user" %>
      <%= nav_link "Doctors",      doctors_path,      "user-md" %>
      <%= nav_link "Institutions", institutions_path, "hospital-o" %>
      <%= nav_link "Mutations",    mutations_path,    "crosshairs" %>
      <%= nav_link "Genotypes",    genotypes_path,    "codepen" %>
      <%= nav_link "Drugs",        drugs_path,        "medkit" %>
      <%= nav_link "Groups",       groups_path,       "group" %>
    </ul>

    <ul class="nav navbar-nav navbar-right navbar-user">
      <li class="dropdown user-dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> John Smith <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#"><i class="fa fa-user"></i> Profile</a></li>
          <li><a href="#"><i class="fa fa-envelope"></i> Inbox <span class="badge">7</span></a></li>
          <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
          <li class="divider"></li>
          <li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <ul class="nav nav-list">
    <li class="nav-header">Menu</li>
    <li><%= link_to "Patients", patients_path %></li>
    <li><%= link_to "Doctors", doctors_path %></li>
    <li><%= link_to "Genotypes", genotypes_path %></li>
    <li><%= link_to "Mutations", mutations_path %></li>
    <li><%= link_to "Drugs", drugs_path %></li>
    <li><%= link_to "Institutions", institutions_path %></li>
  </ul>
</div><!--/.well -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HepatitisAnalysis" %></title>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", :media => "all" %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="wrapper">
      <%= render 'layouts/navbar' %>

      <%= render 'layouts/container' %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>